host/aes_crypto.c: add <stdbool.h> to avoid compiler error
On Linux/OE builds bool is undefined due to missing include.

| In file included from aes_crypto.c:45:0:
| aes_crypto.h:48:5: error: unknown type name 'bool'
|      bool secure);
|      ^~~~
| aes_crypto.c:128:5: error: unknown type name 'bool'
|      bool secure) {
|      ^~~~

Signed-off-by: Peter Griffin <peter.griffin@linaro.org>